# frozen_string_literal: true

source "https://rubygems.org"

gemspec :name => "task2"

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development
